# Generated by Django 5.2.5 on 2025-09-02 14:00

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Artista')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contato')),
                ('website', models.URLField(blank=True, verbose_name='Site')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('profile_image', models.ImageField(blank=True, upload_to='artist_photos/', verbose_name='Foto do Artista')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Evento')),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Evento',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Local')),
                ('map_link', models.URLField(blank=True, verbose_name='Link do Local no Mapa')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contato')),
                ('website', models.URLField(blank=True, verbose_name='Site')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('cover_image', models.ImageField(blank=True, upload_to='venue_covers/', verbose_name='Foto do Local')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Evento')),
                ('original_name', models.CharField(blank=True, max_length=200, verbose_name='Nome Original')),
                ('description', models.TextField(blank=True, verbose_name='Descrição do Evento')),
                ('cover_image', models.ImageField(upload_to='event_covers/', verbose_name='Imagem de Capa')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Avaliação do evento de 0.0 a 5.0', max_digits=3, verbose_name='Avaliação')),
                ('director', models.CharField(blank=True, max_length=200, verbose_name='Direção')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (minutos)')),
                ('distributor', models.CharField(blank=True, max_length=200, verbose_name='Distribuidor')),
                ('country_of_origin', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='País de Origem')),
                ('start_time', models.DateTimeField(verbose_name='Hora de Início')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Encerramento')),
                ('sales_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Início das Vendas')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque na Página Inicial')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo para vendas')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Amigável')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('artists', models.ManyToManyField(blank=True, related_name='events', to='events.artist', verbose_name='Artistas')),
                ('event_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventtype', verbose_name='Tipo de Evento')),
                ('genres', models.ManyToManyField(blank=True, related_name='events', to='events.genre', verbose_name='Gêneros')),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.venue', verbose_name='Local do Evento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.PositiveIntegerField(help_text='Quantidade total de assentos do local', verbose_name='Total de Assentos')),
                ('vip_seats', models.PositiveIntegerField(default=0, verbose_name='Assentos VIP')),
                ('normal_seats', models.PositiveIntegerField(default=0, verbose_name='Assentos Normais')),
                ('openbar_seats', models.PositiveIntegerField(default=0, verbose_name='Assentos OpenBar')),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='seat_maps/', verbose_name='Mapa do Local')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço Ingresso Normal')),
                ('price_vip', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço Ingresso Vip')),
                ('price_openbar', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço Ingresso OpenBar')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_seats', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Assentos do Evento',
                'verbose_name_plural': 'Assentos dos Eventos',
            },
        ),
    ]
