# Generated by Django 5.2.5 on 2025-09-02 14:00

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código do Cupom')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual de Desconto (%)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Válido a partir de')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Válido até')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de usos')),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Usos realizados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('admin_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Taxa de Serviço')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Desconto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'event')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(blank=True, max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_ticket', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('session_key', models.CharField(db_index=True, default='unknown', max_length=40)),
                ('event_name', models.CharField(blank=True, max_length=200)),
                ('event_start_time', models.DateTimeField(blank=True, null=True)),
                ('event_venue', models.CharField(blank=True, max_length=200)),
                ('event_cover_image', models.ImageField(blank=True, null=True, upload_to='cart_event_covers/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cart.order')),
            ],
        ),
    ]
